import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import useClickOutside from "@/hooks/useOutsideClick";
import Modal from "@/components/organisms/Modal";
import Navbar from '@/components/organisms/Navbar';
import HomePage from '@/components/pages/Home'
import Register from "@/components/pages/Register";
import styles from '../styles/Home.module.css'
import UnauthenticatedLayout from 'src/layouts/UnauthenticatedLayout';

const Home: NextPage = () => {
  const modalRef = React.useRef<HTMLDivElement>(null);
  const [showModal, setShowModal] = React.useState(false);

  useClickOutside(modalRef, () => setShowModal(false));
  return (
    <>
    {showModal ? (
      <Modal ref={modalRef} setShowModal={setShowModal} dark>
        <Register />
      </Modal>
    ) : (
      ""
    )}
    <div className={styles.container}>
      <Head>
        <title>Trip Advisor | A mock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <UnauthenticatedLayout showModal={showModal} setShowModal={setShowModal}>
     <HomePage />
     </UnauthenticatedLayout>
    </div>
    </>
  )
}

export default Home
